FROM node:20-alpine AS builder
WORKDIR /usr/src/app

COPY package*.json ./
RUN npm ci

COPY . ./

ARG VITE_API_URL=/flair/api
ARG VITE_APP_URL=https://thinkpad-t480s.tail33c8ae.ts.net/flair/
ARG VITE_BASE_PATH=/flair/
ARG VITE_EMAIL_UI_URL=http://127.0.0.1:8025
ENV VITE_API_URL=$VITE_API_URL \
    VITE_APP_URL=$VITE_APP_URL \
    VITE_BASE_PATH=$VITE_BASE_PATH \
    VITE_EMAIL_UI_URL=$VITE_EMAIL_UI_URL

RUN npm run build

FROM nginx:alpine
COPY --from=builder /usr/src/app/dist /usr/share/nginx/html
COPY nginx/flair.conf /etc/nginx/conf.d/default.conf

EXPOSE 8080
